### PR TITLE
Implement clipping on beta

### PR DESCRIPTION
**Pull request by oooo26**
- Implement clipping after each primary fitting, see #510 ;
- Add relative pytest;
- R API should be updated for two new parameters `beta_low`, `beta_high`; (TODO)

### CODE REVIEW

**Comment by Mamba413** [comment]
@oooo26 , I have just seen the test file. If either `beta_low` or `beta_high` is set, any bug will occur?

**Comment by oooo26** [comment]
> @oooo26 , I have just seen the test file. If either `beta_low` or `beta_high` is set, any bug will occur?

Thank you for checking! There ais no bug. But let me add more tests on that.

**Comment by oooo26** [comment]
And please also note that:
- C++ code allows `beta_low`>`beta_high`, but it will ignore the beta range limitation if so. Python side will check and raise error;
- If enable normalization, the final beta would be possible to outside the range limitation. Because clipping is implemented during fitting.

**Comment by Mamba413** [comment]
Thanks! I think this is fine, and we can merge it.

**Comment by bbayukari** [comment]
R API has been updated in 96ed869f48a0ba954b1ef101616dbf12ae7cbd3a.

**Pull request merged**
