### PR TITLE
Update something

### PR DESCRIPTION
**Pull request by oooo26**
- delete unused parameters
- pack specific parameters (add function: initial_setting & clear_setting)
- pack restore_for_normal
- restructure gs_path & gs support CV results output
- rewrite screening (now use `algorithmXXX.fit()` and unlink with model_fit.h)
- API update
- simplify algorithm pointer (use `algorithm_list_xxx` uniformly)
- move `beta_size` to Algorithm class

### CODE REVIEW

**Comment by Mamba413** [comment]
Have you checked the code via Pytest?

**Comment by oooo26** [comment]
Yes, it has passed Pytest.

**Comment by Mamba413** [comment]
> Yes, it has passed Pytest.

Have you changed anythings in pytest?

**Comment by oooo26** [comment]
In PCA test, I find the sparse test actually give a dense matrix, so I change it to a `coo_matrix` there. Others are unchanged.

**Pull request merged**
