### PR TITLE
Support editable installation & sklearn estimator check

### PR DESCRIPTION
**Pull request by oooo26**
- support install by `pip install -e .`

### CODE REVIEW

**Comment by Mamba413** [comment]
What is the mean of editable installation? Installation in development mode?

**Comment by oooo26** [comment]
In my opinion, "editable pip install" is to create a link between the source code and Python library, instead of installing a "real" packages. [Here](https://stackoverflow.com/questions/35064426/when-would-the-e-editable-option-be-useful-with-pip-install) is an related answer on stackoverflow. (Sorry I didn't find a detailed official document)

**Comment by oooo26** [comment]
Btw, the Python code coverage test failed...and I am trying to fix it.

**Comment by Mamba413** [comment]
> In my opinion, "editable pip install" is to create a link between the source code and Python library, instead of installing a "real" packages. [Here](https://stackoverflow.com/questions/35064426/when-would-the-e-editable-option-be-useful-with-pip-install) is a related answer on stackoverflow. (Sorry I didn't find a detailed official document)

Have you seen this document: https://setuptools.pypa.io/en/latest/userguide/development_mode.html?

**Comment by Mamba413** [comment]
> Btw, the Python code coverage test failed...and I am trying to fix it.

Thx! I think you can manage it.

**Comment by Mamba413** [comment]
> In my opinion, "editable pip install" is to create a link between the source code and Python library, instead of installing a "real" packages. [Here](https://stackoverflow.com/questions/35064426/when-would-the-e-editable-option-be-useful-with-pip-install) is a related answer on stackoverflow. (Sorry I didn't find a detailed official document)

I believe your summary "In my opinion, 'editable pip install' is to create a link between the source code and Python library, instead of installing a "real" packages." is very reasonable.

**Comment by oooo26** [comment]
Support [estimateor check](https://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_checks.check_estimator.html) for classes in `abess.linear`. 

But those in `abess.decomposition` are not supported, because they do not have `y` parameter, which are different from [estimator defined in scikit-learn](https://scikit-learn.org/stable/developers/develop.html#rolling-your-own-estimator).

**Comment by Mamba413** [comment]
Thx! It seems everything works right now. I also witness some change to adapt to the scikit-learn criteria? If so, it would be better to modify the title of this PR.

**Comment by oooo26** [comment]
Oh yes, I should update the PR.

**Pull request merged**
