### PR TITLE
Contribute a new tutorial: "connect with geomstats"

### PR DESCRIPTION
**Pull request by AnrWang**

### CODE REVIEW

**Comment by Mamba413** [comment]
Hi @AnrWang , thanks for your contribution. Have you followed the contribution guideline? Whether `make html` creates a proper tutorial page.

**Comment by Mamba413** [comment]
@AnrWang , Many thanks! Can you add a thumbnail for this tutorial? This can be done by: (I) putting an image file to https://github.com/abess-team/abess/tree/master/docs/Tutorial/figure; and (ii) setting the thumbnail via `sphinx_gallery_thumbnail_path = = 'Tutorial/figure/geomstats.png'` in `plot_2_geomstats.py` (see https://github.com/abess-team/abess/blob/master/docs/Tutorial/5-scikit-learn-connection/plot_1_scikit_learn.py for a typical setting).

**Comment by AnrWang** [comment]
@Mamba413 ,very thankful. I have modified the file `plot_2_geomstats.py` , and submitted a pull request for the thumbnail.

**Comment by Mamba413** [comment]
@AnrWang , thx! We are grateful for your contribution!

**Pull request merged**
