### PR TITLE
Implement Ordinal Logistics Regression Model

### PR DESCRIPTION
**Pull request by bbayukari**

### CODE REVIEW

**Comment by Mamba413** [comment]
Some checks do not pass. Please fix them.

**Comment by bbayukari** [comment]
debug

**Comment by bbayukari** [comment]
Thanks for your work in master branch, now program has been able to run well in my computer.
But, it still can't pass the check of github, and the only problem comes from git. From the logs, it seems that when deploying to GitHub Pages, the request was rejected. And I didn't find useful ways that can fix it in google.

Here is error logs:

>11 Deploying to GitHub Pages 111111111111111111111111111111111111111111111111111
>Running git remote -v
>origin	https://github.com/abess-team/abess (fetch)
>origin	https://github.com/abess-team/abess (push)
>Running git push --force origin 'HEAD:gh-pages'
>remote: Permission to abess-team/abess.git denied to github-actions[bot].
>fatal: unable to access 'https://github.com/abess-team/abess/': The requested URL returned error: 403
>
>Error: Error: System command 'git' failed, exit status: 128, stdout & stderr were printed
>
>Stack trace:
>  
>  1. pkgdown::deploy_to_branch("./R-package", new_process = FALSE,  ...
>  2. pkgdown:::github_push(dest_dir, commit_message, remote, branch)
>  3. pkgdown:::with_dir(dir, { ...
>  4. base:::force(code)
>  5. pkgdown:::git("push", "--force", remote, paste0("HEAD:", branch))
>  6. callr::run("git", c(...), echo_cmd = echo_cmd, echo = echo, error_on_status ...
>  7. throw(new_process_error(res, call = sys.call(), echo = echo,  ...
>                                                                          
>  x System command 'git' failed, exit status: >128, stdout & stderr were printed

**Comment by Mamba413** [comment]
The issue about GitHub Pages is not essential, it will be fixed after it is merged into the `abess-team/abess` repo.

**Comment by Mamba413** [comment]
Three comments:
1. The issue reported by CodeFactor urges to be addressed. Please see https://abess.readthedocs.io/en/latest/Contributing/Formatting.html for how to format.  
2. The check about `R Build / Installation test for R-package (pull_request)` was canceled. It may result from the instability of Github Action. Sometimes, I also encounter it. 
3. The title of your pull request is not clear, please give more details.

**Comment by Mamba413** [comment]
Thanks for your contribution! I am wonder whether the instruction (https://abess.readthedocs.io/en/latest/Contributing/Formatting.html) is clear. If not, do you have any comments?

**Comment by bbayukari** [comment]
I believe it's very clear and simple for people who use VS Code.

**Comment by Mamba413** [comment]
Thanks for your encouraging feedback!  

First, I skim your PR (https://github.com/abess-team/abess/pull/304/files), and I noticed some duplicated code:  
1. line 1938-1955 and line 2149-2165;
2. line 2084-2095 and line 2101-2112.
Whether these operations can be abstracted as a function in class `abessOrdinal`. 

Second, in line 2064-2071 and line 2073-2081, you truncate `h_diag`. And 1e-7 is a hyper-parameter. I think it would be better to set it as a user-defined parameter at least a variable in class `abessOrdinal` now. 

Third, I believe the `bool condition2` can be abstracted as a function for all of `abessXXX` classes.

**Comment by Mamba413** [comment]
@oooo26 , ordinal classification is support now. Shall we merge it right now?

**Comment by Mamba413** [comment]
@bbayukari ， thanks for your contribution! We going to merge it.

**Comment by oooo26** [comment]
Yes, I think we can merge it. Thank you for your hard work!

**Pull request merged**
