### PR TITLE
[New feature, Python] Support no-intercept model for most GLM models

### PR DESCRIPTION
**Pull request by oooo26**
As issuse #507 and #511 mentioned, we may introduce argument to control whether the intercept is considered or not. If the intercept is dropped, we would assume that the data has been centered.

- Support no-intercept model for `LinearRegression`, `LogisticRegression`, `PoissonRegression`, `MultiTaskRegression`, `MultinomialRegression` and `GammaRegression` when given `fit_intercept=False`;
- Update API document;
- Add pytest: no-intercept models' results are consistent with `scikit-learn`'s;

> Note: R package API will need to adapt the additional parameter `fit_intercept`, see `src/api.h`.

### CODE REVIEW

**Comment by oooo26** [comment]
Cox and Ordinal is not supported because:
- Cox regression does not use intercept;
- Ordinal regression has to consider intercept;

**Comment by Mamba413** [comment]
I just have two more questions. 
- When `fit_intercept=False`, we presume y is centred?  
- Does `abess` can correctly select the effective variables in this case?

**Comment by Mamba413** [comment]
That's pretty good. Gamma regression is much more difficult. Maybe we can address this later.

**Comment by bbayukari** [comment]
R API has been updated in 96ed869f48a0ba954b1ef101616dbf12ae7cbd3a.

**Pull request merged**
